<HTML>
<b> Eloah fonseca Pereira n44,1B</b>
<p>/HTML> Oiii,meu nome é Eloah Fonseca.Este é o meu site que acabei de criar,com ele irei me especializar na robótica,no Github e na computação,além de 
buscar novos conhecimentos na área e me profissionalizar com este ramo. 
index.html 
